Repository agriculture-capstone/agriboard, pull requests merged in 2018-04, with the labels that each got.

#108 Resolving sync module promises
  src/services/Sync/index.ts
Labels: bug

#109 Implementing offline support w/ vuex
  build/service-worker.js
  build/webpack.dev.conf.js
  build/webpack.prod.conf.js
  index.html
  package.json
  src/store/index.ts
  src/styles.scss
  src/views/pages/GateKeeper/index.vue
  types/vue-persistedstate.shim.d.ts
  yarn.lock
Labels: feature

#111 Moath/ab 96/update person
  src/store/getters.ts
  src/store/types.ts
  src/utils/CoreAPI/index.ts
  src/views/pages/ManagePeople/index.vue
Labels: feature, maintenence

#118 Mobile friendly
  config/dev.env.js
  src/App.vue
  src/utils/list/sortAlphabeticalByProp.ts
  src/views/components/AnalyticsGraph/index.vue
  src/views/components/global/MemoBoard/index.vue
  src/views/pages/Analytics/index.vue
  src/views/pages/ManagePeople/index.vue
  src/views/pages/ProductTransactions/index.vue
Labels: feature

#121 Fab color
  src/services/Sync/index.ts
  src/views/components/global/Logo/index.vue
  src/views/pages/ProductTransactions/index.vue
Labels: bug
